apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153

        # Simulate broken external DNS
        forward . 127.0.0.1:55555

        # Normal configuration
        proxy . /etc/resolv.conf {
          policy sequential # needed for workloads to be able to use BOSH-DNS
        }

        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  namespace: kube-system
  name: coredns
